# - platform: generic
#   name: Lidija
#   still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.latitude }},{{ states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.longitude }}&zoom={{states.input_number.map_zoom.state|int}}&size=500x300&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.latitude }},{{ states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.longitude }}&key=AIzaSyCiGPtgXdhLonkWgC-gOxJY94Tn7ToIgFI
#   limit_refetch_to_url_change: true
# - platform: generic
#   name: Christer
#   still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.christer_honor.attributes.latitude }},{{ states.device_tracker.christer_honor.attributes.longitude }}&zoom={{states.input_number.map_zoom.state|int}}&size=500x300&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.christer_honor.attributes.latitude }},{{ states.device_tracker.christer_honor.attributes.longitude }}&key=AIzaSyCiGPtgXdhLonkWgC-gOxJY94Tn7ToIgFI
#   limit_refetch_to_url_change: true
# - platform: generic
#   name: street_view_lidija_gps
#   still_image_url: https://maps.googleapis.com/maps/api/streetview?size=500x300&location={{states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.latitude}},{{states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.longitude}}&key=AIzaSyBDiHI_TisMH-qK4NkXC8YhmRxLCgZufxk
#   limit_refetch_to_url_change: true
# - platform: generic
#   name: street_view_christer_gps
#   still_image_url: https://maps.googleapis.com/maps/api/streetview?size=500x300&location={{states.device_tracker.christer_honor.attributes.latitude}},{{states.device_tracker.christer_honor.attributes.longitude}}&key=AIzaSyBDiHI_TisMH-qK4NkXC8YhmRxLCgZufxk
#   limit_refetch_to_url_change: true
- platform: generic
  name: location_map
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{states.sensor.center_map_on.state}}&zoom={{states.input_number.map_zoom.state|int}}&size=600x300&maptype=roadmap&markers=icon:https://s20.postimg.org/9hd8g5khl/christer.png|{{states.device_tracker.christer_honor.attributes.latitude}},{{states.device_tracker.christer_honor.attributes.longitude}}&markers=icon:https://s20.postimg.org/odbrnqo6h/lidija.png|{{states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.latitude}},{{states.device_tracker.lidija_762061a869904b4d98a3f95645299120.attributes.longitude}}&key=AIzaSyCiGPtgXdhLonkWgC-gOxJY94Tn7ToIgFI
  limit_refetch_to_url_change: true
# - platform: generic
#   name: ISS
#   still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom={{states.input_number.map_zoom_iss.state|int}}&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
#   limit_refetch_to_url_change: true
- platform: generic
  name: weather
  still_image_url: https://api.sat24.com/animated/EU/visual/1/W_dot_%20Europe%20Standard%20Time/5449763' width=400 height=291
  limit_refetch_to_url_change: false
# - platform: generic
#   name: Lindholmsmotet
#   still_image_url: https://images.webcams.travel/original/1475585219-g%C3%B6teborg-lindholmsmotet-%C3%B6st-nord%C3%B6st.jpg?token=webcams.travel:b8c8f5fabcc5c18bd63118e90fbaa32b:1521362592
#   limit_refetch_to_url_change: false
- platform: generic
  name: regn
  still_image_url: https://api.sat24.com/crop?type=visual5hdcomplete&lat=57.6508&lon=11.9967&width=300&height=300&zoom=1.00&continent=eu
  limit_refetch_to_url_change: false
- platform: generic
  name: temperatur
  still_image_url: https://sirocco.accuweather.com/adc_images2/english/forecast/hgh/640x480/SN_todhigh.gif
  limit_refetch_to_url_change: false
- platform: generic
  name: goteborg
  still_image_url: https://ecn.t3.tiles.virtualearth.net/tiles/ho120032?g=671&mkt=en-us
  limit_refetch_to_url_change: false
- platform: generic
  name: Pollenkalender
  still_image_url: http://pollenrapporten.se/images/18.314e02dd13d69872ec06b/1367827614471/Pollenkalender_pollen.png
  limit_refetch_to_url_change: false
